apiVersion: v1
kind: Service
metadata:
  name: nginix-load
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 8001
      nodePort: 31002
      targetPort: 80
