---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Malli-Cluster
  region: us-east-2

vpc:
  id: vpc-08aadb3ec42091eae
  cidr: "172.31.0.0/16"
  subnets:
    public:
      public-one:
        id: subnet-05c48fec2f306ea43
      public-two:
        id: subnet-03fd9fa10508ce3f7
      public-three:
        id: subnet-0e17431081205dc71
    

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 1
    subnets:
      - public-one
      - public-two
  - name: ng-2
    instanceType: t2.medium
    desiredCapacity: 1
    subnets:
      - public-three
