apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tom-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:  
    metadata:
      name: tomcat-pod
      labels:
        app: tomcat
    spec:
      containers:
        - name: tom-container
          image: te97ja/multistage:latest

